[project]
name = "luagenny"
cmake-before = """
"""

[vcpkg]
version = "2022.05.10"
packages = [
    "pegtl",
    "lua",
    "sol2"
]

[fetch-content.sdkgenny]
git = "https://github.com/cursey/sdkgenny.git"
tag = "eb06f76d72454394c4ef4f2da4fae05bb82db82a" 


[find-package]
pegtl = {}
lua = { required = false }
sol2 = { required = false }

[conditions]
static = "${VCPKG_TARGET_TRIPLET} MATCHES \".+static\""

[target.luagenny]
type = "static"
sources = [
    "src/**.cpp",
    "src/**.hpp",
]
link-libraries = [
    "lua",
    "sol2::sol2",
    "sdkgenny"
]
compile-features = ["cxx_std_20"]
compile-options = ["/bigobj"]

[target.test]
type = "executable"
sources = ["test/Main.cpp"]
include-directories = [
    "src",
]
link-libraries = [
    "lua",
    "sol2::sol2",
    "luagenny",
    "sdkgenny"
]
compile-features = ["cxx_std_20"]

[[install]]
targets = ["luagenny", "test"]
destination = "bin"