[project]
name = "luagenny"
cmake-before="""
add_compile_options($<$<CXX_COMPILER_ID:MSVC>:/MP>)
"""

[vcpkg]
version = "2022.08.15"
packages = [
    "pegtl",
    "lua",
    "sol2"
]

[fetch-content.sdkgenny]
git = "https://github.com/cursey/sdkgenny.git"
tag = "2bf398fdcc48346486b0e754a93da21fb788e245" 


[find-package]
pegtl = {}
lua = { required = false }
sol2 = { required = false }

[conditions]
static = "${VCPKG_TARGET_TRIPLET} MATCHES \".+static\""

[target.luagenny]
type = "static"
sources = [
    "src/**.cpp",
    "src/**.hpp",
]
link-libraries = [
    "lua",
    "sol2",
    "sdkgenny"
]
include-directories = [
    "include",
]

compile-features = ["cxx_std_20"]
compile-options = ["/bigobj"]
alias = "luagenny::luagenny"

[target.test]
type = "executable"
sources = ["test/Main.cpp"]
include-directories = [
    "src",
]
link-libraries = [
    "lua",
    "sol2",
    "luagenny::luagenny",
    "sdkgenny::sdkgenny"
]
compile-features = ["cxx_std_20"]

[[install]]
targets = ["luagenny", "test"]
destination = "bin"