[project]
name = "luagenny"
cmake-before="""
add_compile_options($<$<CXX_COMPILER_ID:MSVC>:/MP>)
option(LUAGENNY_BUILD_STATIC OFF)
message("${LUAGENNY_BUILD_STATIC}")
"""

[vcpkg]
version = "2022.08.15"
packages = [
    "pegtl",
    "lua",
    "sol2"
]

[fetch-content.sdkgenny]
git = "https://github.com/cursey/sdkgenny.git"
tag = "e45198d46e17de4b251704122b8c74837cae773e" 


[find-package]
pegtl = {}
lua = { required = false }
sol2 = { required = false }

[conditions]
static = "LUAGENNY_BUILD_STATIC"
shared = "NOT LUAGENNY_BUILD_STATIC"

[target.luagenny_static]
condition = "static"
type = "static"
sources = [
    "src/**.cpp",
    "src/**.hpp",
]
link-libraries = [
    "lua",
    "sol2",
    "sdkgenny"
]
include-directories = [
    "include",
]
compile-features = ["cxx_std_20"]
compile-options = ["/bigobj"]
compile-definitions = []
alias = "luagenny::luagenny"

[target.luagenny_static.properties]
OUTPUT_NAME="luagenny"

[target.luagenny_shared]
condition = "shared"
type = "shared"
sources = [
    "src/**.cpp",
    "src/**.hpp",
]
link-libraries = [
    "lua",
    "sol2",
    "sdkgenny"
]
include-directories = [
    "include",
]
compile-features = ["cxx_std_20"]
compile-options = ["/bigobj"]
compile-definitions = ["LUAGENNY_EXPORTS"]
alias = "luagenny::luagenny"

[target.luagenny_shared.properties]
OUTPUT_NAME="luagenny"

[target.repl]
type = "executable"
sources = ["test/Main.cpp"]
include-directories = [
    "src",
]
link-libraries = [
    "lua",
    "sol2",
    "luagenny::luagenny",
    "sdkgenny::sdkgenny"
]
compile-features = ["cxx_std_20"]

[[test]]
name = "mytest"
command = "$<TARGET_FILE:repl>"
arguments = ["--test", "${CMAKE_CURRENT_SOURCE_DIR}/test/test.lua"]
configurations = ["Debug", "Release", "RelWithDebInfo", "MinSizeRelease"]

[[install]]
condition = "shared"
targets = ["luagenny_shared", "repl"]
destination = "bin"

[[install]]
condition = "static"
targets = ["luagenny_static", "repl"]
destination = "bin"
