[project]
name = "sdkgenny-lua"
cmake-before = """
"""

[vcpkg]
version = "2022.05.10"
packages = [
    "pegtl",
    "lua",
    "sol2"
]

[fetch-content.sdkgenny]
git = "https://github.com/cursey/sdkgenny.git"
tag = "f03026eaced3bd033e201bc7d1c9d9d348054113" 


[find-package]
pegtl = {}
lua = { required = false }
sol2 = { required = false }

[conditions]
static = "${VCPKG_TARGET_TRIPLET} MATCHES \".+static\""

[target.sdkgenny-lua]
type = "static"
sources = [
    "src/**.cpp",
    "src/**.hpp",
]
link-libraries = [
    "lua",
    "sol2::sol2",
    "sdkgenny"
]
compile-features = ["cxx_std_20"]
compile-options = ["/bigobj"]

[target.test]
type = "executable"
sources = ["test/Main.cpp"]
include-directories = [
    "src",
]
link-libraries = [
    "lua",
    "sol2::sol2",
    "sdkgenny-lua",
    "sdkgenny"
]
compile-features = ["cxx_std_20"]
