[project]
name = "sdkgenny-lua"

[vcpkg]
version = "2022.05.10"
packages = [
    "spdlog",
]

[fetch-content]
sdkgenny = { git = "https://github.com/cursey/sdkgenny.git", tag = "f03026eaced3bd033e201bc7d1c9d9d348054113" }

[find-package]
spdlog = {}

[conditions]
static = "${VCPKG_TARGET_TRIPLET} MATCHES \".+static\""

[target.sdkgenny-lua]
type = "static"
sources = [
    "src/**.cpp",
    "src/**.hpp",
]
link-libraries = [
    "spdlog::spdlog"
]
compile-features = ["cxx_std_17"]

[target.sdkgenny-lua.properties]
static.MSVC_RUNTIME_LIBRARY = "MultiThreaded$<$<CONFIG:Debug>:Debug>"

[target.test]
type = "executable"
sources = ["test/Main.cpp"]
link-libraries = [
    "sdkgenny-lua",
]
compile-features = ["cxx_std_17"]
