[project]
name = "sdkgenny-lua"

[vcpkg]
version = "2022.05.10"
packages = [
    "fmt",
    "spdlog",
    "pegtl",
    "sol2",
]

[fetch-content]
sdkgenny = { git = "https://github.com/cursey/sdkgenny.git", tag = "f03026eaced3bd033e201bc7d1c9d9d348054113" }

[find-package]
fmt = {}
spdlog = {}
pegtl = {}
sol2 = {}

[conditions]
static = "${VCPKG_TARGET_TRIPLET} MATCHES \".+static\""

[target.sdkgenny-lua]
type = "static"
sources = [
    "src/**.cpp",
    "src/**.hpp",
]
link-libraries = [
    "fmt::fmt",
    "spdlog::spdlog",
    "sol2::sol2",
    "sdkgenny"
]
compile-features = ["cxx_std_17"]
compile-options = ["/bigobj"]

[target.sdkgenny-lua.properties]
static.MSVC_RUNTIME_LIBRARY = "MultiThreaded$<$<CONFIG:Debug>:Debug>"

[target.test]
type = "executable"
sources = ["test/Main.cpp"]
include-directories = [
    "src",
]
link-libraries = [
    "sdkgenny-lua",
]
compile-features = ["cxx_std_17"]
